<?xml version="1.0" encoding="utf-8"?><Database Name="QLSHOPGIAY" Class="DataDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.ADMIN" Member="ADMINs">
    <Type Name="ADMIN">
      <Column Name="MaRole" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="TenAdmin" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="TaiKhoanAdmin" Type="System.String" DbType="NVarChar(100) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MatKhauAdmin" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="ROLE_ADMIN" Member="ROLE" ThisKey="MaRole" OtherKey="MaRole" Type="ROLE" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SIZE" Member="SIZEs">
    <Type Name="SIZE">
      <Column Name="MaSize" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenSize" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Association Name="SIZE_CHITIETDH" Member="CHITIETDHs" ThisKey="MaSize" OtherKey="MaSize" Type="CHITIETDH" />
      <Association Name="SIZE_CHITIETSIZE" Member="CHITIETSIZEs" ThisKey="MaSize" OtherKey="MaSize" Type="CHITIETSIZE" />
      <Association Name="SIZE_GIOHANG" Member="GIOHANGs" ThisKey="MaSize" OtherKey="MaSize" Type="GIOHANG" />
    </Type>
  </Table>
  <Table Name="dbo.CHITIETDH" Member="CHITIETDHs">
    <Type Name="CHITIETDH">
      <Column Name="MaDH" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaSP" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaSize" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SLMua" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GiaMua" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="SIZE_CHITIETDH" Member="SIZE" ThisKey="MaSize" OtherKey="MaSize" Type="SIZE" IsForeignKey="true" />
      <Association Name="DONHANG_CHITIETDH" Member="DONHANG" ThisKey="MaDH" OtherKey="MaDH" Type="DONHANG" IsForeignKey="true" />
      <Association Name="SANPHAM_CHITIETDH" Member="SANPHAM" ThisKey="MaSP" OtherKey="MaSP" Type="SANPHAM" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CHITIETSIZE" Member="CHITIETSIZEs">
    <Type Name="CHITIETSIZE">
      <Column Name="MaSP" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaSize" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="SIZE_CHITIETSIZE" Member="SIZE" ThisKey="MaSize" OtherKey="MaSize" Type="SIZE" IsForeignKey="true" />
      <Association Name="SANPHAM_CHITIETSIZE" Member="SANPHAM" ThisKey="MaSP" OtherKey="MaSP" Type="SANPHAM" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DANHMUC" Member="DANHMUCs">
    <Type Name="DANHMUC">
      <Column Name="MaDM" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenDM" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="DanhMucCha" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="DANHMUC_SANPHAM" Member="SANPHAMs" ThisKey="MaDM" OtherKey="MaDM" Type="SANPHAM" />
    </Type>
  </Table>
  <Table Name="dbo.DONHANG" Member="DONHANGs">
    <Type Name="DONHANG">
      <Column Name="MaDH" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaKH" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TongTien" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="NgayMua" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="ThanhToan" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TrangThai" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="DONHANG_CHITIETDH" Member="CHITIETDHs" ThisKey="MaDH" OtherKey="MaDH" Type="CHITIETDH" />
      <Association Name="KHACHHANG_DONHANG" Member="KHACHHANG" ThisKey="MaKH" OtherKey="MaKH" Type="KHACHHANG" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.GIOHANG" Member="GIOHANGs">
    <Type Name="GIOHANG">
      <Column Name="MaKH" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaSP" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaSize" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ThanhTien" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="SIZE_GIOHANG" Member="SIZE" ThisKey="MaSize" OtherKey="MaSize" Type="SIZE" IsForeignKey="true" />
      <Association Name="KHACHHANG_GIOHANG" Member="KHACHHANG" ThisKey="MaKH" OtherKey="MaKH" Type="KHACHHANG" IsForeignKey="true" />
      <Association Name="SANPHAM_GIOHANG" Member="SANPHAM" ThisKey="MaSP" OtherKey="MaSP" Type="SANPHAM" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.KHACHHANG" Member="KHACHHANGs">
    <Type Name="KHACHHANG">
      <Column Name="MaKH" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaRole" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="TenKH" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="MatKhauKH" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="SDT" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Gmail" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="ResetCode" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ResetCodeSentTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="KHACHHANG_DONHANG" Member="DONHANGs" ThisKey="MaKH" OtherKey="MaKH" Type="DONHANG" />
      <Association Name="KHACHHANG_GIOHANG" Member="GIOHANGs" ThisKey="MaKH" OtherKey="MaKH" Type="GIOHANG" />
      <Association Name="ROLE_KHACHHANG" Member="ROLE" ThisKey="MaRole" OtherKey="MaRole" Type="ROLE" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ROLE" Member="ROLEs">
    <Type Name="ROLE">
      <Column Name="MaRole" Type="System.Boolean" DbType="Bit NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RoleName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="ROLE_ADMIN" Member="ADMINs" ThisKey="MaRole" OtherKey="MaRole" Type="ADMIN" />
      <Association Name="ROLE_KHACHHANG" Member="KHACHHANGs" ThisKey="MaRole" OtherKey="MaRole" Type="KHACHHANG" />
    </Type>
  </Table>
  <Table Name="dbo.SANPHAM" Member="SANPHAMs">
    <Type Name="SANPHAM">
      <Column Name="MaSP" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaDM" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TenSP" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Mota" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="AnhMinhHoa" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="MauSP" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="GiaSP" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ThuongHieu" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="ChatLieu" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="KieuDang" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="SANPHAM_CHITIETDH" Member="CHITIETDHs" ThisKey="MaSP" OtherKey="MaSP" Type="CHITIETDH" />
      <Association Name="SANPHAM_CHITIETSIZE" Member="CHITIETSIZEs" ThisKey="MaSP" OtherKey="MaSP" Type="CHITIETSIZE" />
      <Association Name="SANPHAM_GIOHANG" Member="GIOHANGs" ThisKey="MaSP" OtherKey="MaSP" Type="GIOHANG" />
      <Association Name="DANHMUC_SANPHAM" Member="DANHMUC" ThisKey="MaDM" OtherKey="MaDM" Type="DANHMUC" IsForeignKey="true" />
    </Type>
  </Table>
</Database>